# Readings & Resources {#resources}

This page is a collection of books, papers, presentations, podcasts, and links to other resources that trainees have compiled. They span a variety of topics, some more relevant than others. They are also for various audiences, some explicitly academic/scholarly and others written for a broad public audience. We collect foundational citations, current and interesting research, work from diverse researchers, and conversations around current events that relate to our discussions, training, and/or research. 
Although we have collected these resources for our own use, we hope this page will be useful to others, and we encourage revisions and updates to this document. 

Next Book (Fall 2021) -- Atlas of AI: Power, Politics, and the Planetary Costs of Artificial Intelligence [@crawford_atlas_2021], available for purchase [here](https://bookshop.org/books/atlas-of-ai-power-politics-and-the-planetary-costs-of-artificial-intelligence/9780300209570) or probably Amazon


## Book Club Picks

Notes for books we have read can be found in Chapter \@ref(readingnotes).

- **Fall 2020.** Data Feminism [@dignazio_data_2020], notes in Ch \@ref(datafem)
  * *This was our first book as a group (we were inspired by the virtual reading group, linked below). We think it is a good read for anyone joining the group or just interested in reading about these topics.*
  * Recordings of the author-led online reading group and sketchnotes are a wonderful resource, [here](http://datafeminism.io/blog/book/data-feminism-reading-group/)
  * Many of the resources included in our list below are cited in DataFem

- **Spring 2021.** Race After Technology: Abolitionist Tools for the New Jim Code [@benjamin_race_2019], notes in Ch \@ref(raceaftertech)
  * *This book got us thinking about race in society and in technology.*
  * Dr. Benjamin gave some wonderful keynote presentations as we were discussing the book (eg, keynote presentations at AMIA 2020 and [CHI 2021](https://youtu.be/kDcz44ifdQw))

- **Summer 2021.** Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy [@oneil_weapons_2016], notes in Ch \@ref(womd)
  * *Although not directly addressing healthcare or informatics, this book provides an overview and framework of what can go wrong with mathmatical modeling, including devestating real-world implications. It is an enjoyable and accessible read for a non-technical audience.*

- **Fall 2021 (current).** Atlas of AI: Power, Politics, and the Planetary Costs of Artificial Intelligence [@crawford_atlas_2021], notes in Ch \@ref(aoa)


## Comprehensive List


### Bias (eg, due to race, gender) + Technology

- Race After Technology: Abolitionist Tools for the New Jim Code [@benjamin_race_2019]
- Algorithms of Oppression: How Search Engines Reinforce Racism [@noble_algorithms_2018]
- Automating Inequality: How High-Tech Tools Profile, Police, and Punish the Poor [@eubanks_automating_2018]
- Invisible Women: Exposing Data Bias in a World Designed for Men [@perez_invisible_2019]
- Doing Harm: The Truth About How Bad Medicine and Lazy Science Leave Women Dismissed, Misdiagnosed, and Sick [@dusenbery_doing_2018]

- Technically Wrong: Sexist Apps, Biased Algorithms, and Other Threats of Toxic Tech [@wachter_technically_2017]
- Glitch Feminism [@russell_glitch_2020], [website](https://www.legacyrussell.com/GLITCHFEMINISM) also includes videos
- Design Justice [@costanzachock_design_2020], and wonderful [website](https://designjustice.org/)


- Coded Bias (documentary) [@codedbias_2020], notes in Ch \@ref(codedbias)

- Mimi Onuoha (video) [How We Became Machine Readable](https://vimeo.com/233011125)


### Data Science + Society

- Data Feminism [@dignazio_data_2020]
  * Academic publications (journal articles) by book authors: [@dignazio_feminist_2016; @balaam_hacking_2017; @klein_seven_2020; @dignazio_feminist_2016; @garcia_no_2020]
  * Feminist HCI: [@bardzell_feminist_2010; @bellini_feminist_2018]
  
- Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy [@oneil_weapons_2016]

- Atlas of AI: Power, Politics, and the Planetary Costs of Artificial Intelligence [@crawford_atlas_2021]
  * [Kate Crawford](https://www.katecrawford.net/about.html) discussing infrastructures of technical systems: [here](https://www.youtube.com/watch?v=pRpSW6T_Wuo) and [here](https://youtu.be/v8wi3ya-y3g)
  
  
- The Alignment Problem [@christian_allignment_2020]
- Ghost Work: How to Stop Silicon Valley from Building a Global Underclass [@gray_suri_ghost_2019]
- The Age of Surveillance Capitalism [@zuboff_surveillance_2019]



- AI and Society (podcasts), [Stewart Russell](https://people.eecs.berkeley.edu/~russell/): [Have the Machines Taken Over?](https://www.youtube.com/watch?v=jmbfQ3mjHWI) and [3 Principles for Creating Safer AI](https://www.ted.com/talks/stuart_russell_3_principles_for_creating_safer_ai/up-next)


- NYT Presents: Rabbit Hole (podcast) [@rabbit_hole_2020]
  * About shaping, and being shaped, by the internet
- Health 2049 (podcast) [@health_2049]
  * About using storytelling and design strategy to address broad challenges in healthcare


### Indigenous Knowledge

- Indigenous Statistics: A Quantitative Research Methodology [@walter_indigenous_2016]
- Braiding Sweetgrass: Indigenous Wisdom, Scientific Knowledge, and the Teachings of Plants [@kimmerer_braiding_2015]

- "Studying Those Who Study Us" (talk) [@tallbear_2020]


### (In)Justice in Medicine


- The Hospital: Life, Death, and Dollars in a Small American Town [@alexander_hospital_2021]

- Medical Apartheid: A Dark History of Medical Experimentation on Black Americans from Colonial Times to the Present [@washington_medical_2008]



### Human-Centered; Storytelling


- Dr. Rita Charon, on the creation of the field of Narrative Medicine 


### Higher Ed

- Unequal expectations: First-generation and continuing-generation students’ anticipated relationships with doctoral advisors in STEM [@wofford_unequal_2021]
- A Field Guide to Grad School: Uncovering the Hidden Curriculum [@calarco_field_2020]






## Academic Scholarship

- "An actionable anti-racism plan for geoscience organizations". Ali et al., Nature 2021 [@ali_antiracism_2021]
- "Embracing Four Tensions in Human-Computer Interaction Research with Marginalized People". Liang, Munson & Kientz, CHI 2021 [@liang_HCI_2021]
- "Digital Phenotyping and Digital Psychotropic Drugs: Mental Health Surveillance Tools That Threaten Human Rights". Cosgrove et al., Health and Human Rights Journal 2020 [@cosgrove_phenotyping_drugs_2020]




## Network & Citational Justice




## Other Links to Outside Resources

- Columbia University Data Science Institute, [Race + Data Science Resources](https://datascience.columbia.edu/diversity/race-data-science-resources/), curated by Dr. Desmond Patton


- [Shut Down Academia Resource Page](https://www.shutdownstem.com/resources)
- [Particles of Justice BLM Resource Page](https://www.particlesforjustice.org/resources)


- [Critical Race and Digital Studies Syllabus](https://criticalracedigitalstudies.com/syllabus/)

- Anti-Racism [google doc](https://docs.google.com/document/d/1hpub-jkm9cLzJWqZSsETqbE6tZ13Q0UbQz--vQ2avEc/preview?pru=AAABcsN4aJw*6TW1VkdMyvfZOMHsSVmsYg), [another google doc](https://docs.google.com/document/d/1BRlF2_zhNe86SGgHa6-VlBO-QgirITwCTugSfKie5Fs/preview?pru=AAABcsN4Mio*zMsO1fI_2ymsmqtXb0ZAZw)
- Anti-Oppression [google sheet](https://docs.google.com/spreadsheets/d/1RkJ-uqKzyhRc6ZxRh2mtcBG5vmGM3hi5aiAvQXPGPR0/edit#gid=1433041826)
- Concrete Steps for Recruiting, Supporting, and Advancing Underrepresented Minoritized Scientists [google doc](https://docs.google.com/document/d/1Ic6bil2AvrQmPFUcUyxcw_FumofKkUo3VLsU7qG0cTk/preview?pru=AAABcsMdcOw*rqbF-IyZSoJBfHrpIZeWUw#)

- [Radical AI](https://radicalai.net/)
- [Queer in AI](https://sites.google.com/view/queer-in-ai//)


Columbia Resources 

- [Columbia GSAS Diversity and Inclusion](https://gsas.columbia.edu/our-intellectual-community/diversity)
- Student groups and support for BIPOC students/affiliates
- Ombudsman etc


